import { Button } from "@nextui-org/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Arpanet APUSH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button>Hello Ben</Button>
      </main>
    </>
  );
}
